### PR TITLE
New Sunspec inverter agent added to NREL agents

### PR DESCRIPTION
**Pull request by sivasath-NREL**
The new agent added implements the Sunspec protocol for DER client (Inverter) in particular.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron-applications/pull/60%23issuecomment-426392890%22%2C%20%22https%3A//github.com/VOLTTRON/volttron-applications/pull/60%23issuecomment-426820294%22%2C%20%22https%3A//github.com/VOLTTRON/volttron-applications/pull/60%23issuecomment-427114854%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron-applications/pull/60%23issuecomment-426392890%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looking%20through%20your%20code%20the%20entire%20interface%20boils%20down%20to%20get%20and%20set%20device%20values%20RPC%20calls%20%28which%20is%20fine%29.%20Your%20agent%20also%20polls%20the%20device%20periodically%20for%20it%27s%20current%20state.%20This%20makes%20me%20wonder%20if%20it%27s%20desirable%20to%20turn%20this%20into%20an%20Interface%20for%20the%20Master%20Driver%20Agent.%20It%20would%20not%20necessarily%20require%20that%20this%20code%20be%20moved%20under%20the%20umbrella%20of%20that%20agent%2C%20although%20that%20is%20usually%20where%20driver%20interface%20code%20lives.%5Cr%5Cn%5Cr%5CnThe%20advantages%20of%20making%20this%20a%20driver%20interface%20include%3A%20%5Cr%5Cn%20-%20Automatic%20data%20gathering%20and%20storing%20in%20any%20historian%20supported%20database.%5Cr%5Cn%20-%20Common%20agent%20interface.%20Agents%20don%27t%20need%20to%20be%20aware%20of%20the%20underlying%20protocol%20to%20send%20commands%20to%20the%20device%20or%20subscribe%20to%20what%20is%20published%20by%20the%20device.%5Cr%5Cn%20-%20Configuration%20store%20support.%5Cr%5Cn%20-%20Built%20in%20polling%20functionality%20that%20will%20publish%20polled%20data%20to%20the%20device.%5Cr%5Cn%20-%20Some%20other%20stuff%20that%20I%27m%20probably%20forgetting.%22%2C%20%22created_at%22%3A%20%222018-10-02T19%3A02%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%2C%20%7B%22body%22%3A%20%22Although%20it%27s%20getting%20and%20setting%20device%20values%2C%20it%20reads%20different%20registers%20and%20different%20models.%20In%20the%20future%2C%20it%27s%20supposed%20to%20be%20extended%20to%20interact%20with%20a%20utility%27s%20web%20interface%20and%20have%20scheduling%20functionality.%20So%20we%20can%20leave%20the%20agent%20here%20and%20add%20an%20interface%20to%20the%20Master%20Driver.%20In%20that%20case%2C%20I%20can%20create%20a%20pull%20request%20in%20the%20master%20branch.%20%22%2C%20%22created_at%22%3A%20%222018-10-03T22%3A08%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/33468615%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sivasath-NREL%22%7D%7D%2C%20%7B%22body%22%3A%20%22Would%20it%20make%20sense%20to%20create%20the%20driver%20interface%20as%20a%20thin%20wrapper%20that%20does%20RPC%20calls%20to%20this%20agent%3F%5Cr%5CnAlso%2C%20you%20could%20add%20the%20driver%20interface%20to%20the%20applications%20project%20as%20part%20of%20the%20package%20for%20this%20agent.%20It%20is%20pretty%20simple%20to%20use%20a%20symbolic%20link%20to%20make%20the%20driver%20available%20to%20the%20Master%20driver.%20%28The%20installation%20packing%20step%20just%20does%20the%20right%20thing.%29%22%2C%20%22created_at%22%3A%20%222018-10-04T18%3A03%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/VOLTTRON/volttron-applications/pull/60#issuecomment-426392890'>General Comment</a></b>
- <a href='https://github.com/kmonson'></a> Looking through your code the entire interface boils down to get and set device values RPC calls (which is fine). Your agent also polls the device periodically for it's current state. This makes me wonder if it's desirable to turn this into an Interface for the Master Driver Agent. It would not necessarily require that this code be moved under the umbrella of that agent, although that is usually where driver interface code lives.
The advantages of making this a driver interface include:
- Automatic data gathering and storing in any historian supported database.
- Common agent interface. Agents don't need to be aware of the underlying protocol to send commands to the device or subscribe to what is published by the device.
- Configuration store support.
- Built in polling functionality that will publish polled data to the device.
- Some other stuff that I'm probably forgetting.
- <a href='https://github.com/sivasath-NREL'></a> Although it's getting and setting device values, it reads different registers and different models. In the future, it's supposed to be extended to interact with a utility's web interface and have scheduling functionality. So we can leave the agent here and add an interface to the Master Driver. In that case, I can create a pull request in the master branch.
- <a href='https://github.com/kmonson'></a> Would it make sense to create the driver interface as a thin wrapper that does RPC calls to this agent?
Also, you could add the driver interface to the applications project as part of the package for this agent. It is pretty simple to use a symbolic link to make the driver available to the Master driver. (The installation packing step just does the right thing.)

<a href='https://www.codereviewhub.com/VOLTTRON/volttron-applications/pull/60?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/VOLTTRON/volttron-applications/pull/60?approve=1'></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron-applications/pull/60'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by craig8** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/VOLTTRON/volttron-applications/pull/60'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kmonson** [comment]
Looking through your code the entire interface boils down to get and set device values RPC calls (which is fine). Your agent also polls the device periodically for it's current state. This makes me wonder if it's desirable to turn this into an Interface for the Master Driver Agent. It would not necessarily require that this code be moved under the umbrella of that agent, although that is usually where driver interface code lives.

The advantages of making this a driver interface include: 
 - Automatic data gathering and storing in any historian supported database.
 - Common agent interface. Agents don't need to be aware of the underlying protocol to send commands to the device or subscribe to what is published by the device.
 - Configuration store support.
 - Built in polling functionality that will publish polled data to the device.
 - Some other stuff that I'm probably forgetting.

**Comment by sivasath-NREL** [comment]
Although it's getting and setting device values, it reads different registers and different models. In the future, it's supposed to be extended to interact with a utility's web interface and have scheduling functionality. So we can leave the agent here and add an interface to the Master Driver. In that case, I can create a pull request in the master branch.

**Comment by kmonson** [comment]
Would it make sense to create the driver interface as a thin wrapper that does RPC calls to this agent?
Also, you could add the driver interface to the applications project as part of the package for this agent. It is pretty simple to use a symbolic link to make the driver available to the Master driver. (The installation packing step just does the right thing.)

**Review by rlutes — APPROVED** [review]

**Pull request merged**
